"""
Django settings for PBL project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read from environment, falling back to current default for local/dev
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-^_^z+g@c_wo-@$zq%wx4e^#9l2$)!=^rhv6=jqq_32ele0b107')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True').lower() in ('1', 'true', 'yes', 'on')

# Allow LAN access - Add your computer's IP address here
ALLOWED_HOSTS = [h for h in os.getenv('DJANGO_ALLOWED_HOSTS', '').split(',') if h] or ['127.0.0.1', 'localhost', 'testserver', '*']

# CSRF Trusted Origins for Railway deployment
CSRF_TRUSTED_ORIGINS = [
    origin.strip() 
    for origin in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') 
    if origin.strip()
]

#ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '192.168.254.105']
#SESSION_COOKIE_DOMAIN = None
#SESSION_COOKIE_SECURE = False
#CSRF_COOKIE_SECURE = False
#CSRF_TRUSTED_ORIGINS = ['http://192.168.254.105']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "myapp"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # For static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Authentication settings
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

LOGIN_URL = 'homepage2'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'homepage2'

ROOT_URLCONF = 'MEDISAFE_PBL.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [
        BASE_DIR / 'templates',
        BASE_DIR / 'myapp' / 'templates',
        BASE_DIR / 'myapp' / 'features' / 'admin' / 'templates',
        BASE_DIR / 'myapp' / 'features' / 'consultations' / 'templates',
        BASE_DIR / 'myapp' / 'features' / 'dashboard' / 'templates',
        BASE_DIR / 'myapp' / 'features' / 'home' / 'templates',
        BASE_DIR / 'myapp' / 'features' / 'medical' / 'templates',
        BASE_DIR / 'myapp' / 'features' / 'profiles' / 'templates',
        BASE_DIR / 'myapp' / 'features' / 'healthtools' / 'templates',
        BASE_DIR / 'myapp' / 'features' / 'conditions',
        BASE_DIR / 'myapp' / 'features' / 'doctors',
    ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MEDISAFE_PBL.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Railway provides DATABASE_URL, parse it if available
DATABASE_URL = os.getenv('DATABASE_URL')
if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600)
    }
else:
    # Fallback to Supabase connection for local development
    DATABASES = {
        'default': {
            'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.postgresql'),
            'NAME': os.getenv('DB_NAME', 'postgres'),
            'USER': os.getenv('DB_USER', 'postgres.wqoluwmdzljpvzimjiyr'),
            'PASSWORD': os.getenv('DB_PASSWORD', 'Chowkings6229521'),
            'HOST': os.getenv('DB_HOST', 'aws-1-ap-southeast-1.pooler.supabase.com'),
            'PORT': os.getenv('DB_PORT', '5432'),
            'OPTIONS': {
                'sslmode': os.getenv('DB_SSLMODE', 'require'),
            },
            'CONN_MAX_AGE': int(os.getenv('DB_CONN_MAX_AGE', '600')),
        }
    }
# Custom User Model
AUTH_USER_MODEL = 'myapp.User'  

# (deduplicated) Authentication backends already defined above


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Session configuration
SESSION_COOKIE_AGE = 86400  # 24 hours
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
SESSION_COOKIE_HTTPONLY = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Media files (User uploaded files)
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'myapp' / 'static',
    BASE_DIR / 'myapp' / 'features' / 'doctors',
    BASE_DIR / 'media',  # Add media folder to static files for Railway deployment
]

# WhiteNoise configuration for production static file serving
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (User uploaded files) - served as static in production
MEDIA_URL = '/static/'
MEDIA_ROOT = BASE_DIR / 'media'
# Supabase Storage Configuration
SUPABASE_URL = os.getenv('SUPABASE_URL', 'https://wqoluwmdzljpvzimjiyr.supabase.co')
# Use service_role key for backend operations (has full access)
SUPABASE_SERVICE_KEY = os.getenv('SUPABASE_SERVICE_KEY', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indxb2x1d21kemxqcHZ6aW1qaXlyIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczMjc5NzY2NCwiZXhwIjoyMDQ4MzczNjY0fQ.T_OElQDKWJt0Oq4Sg0SoHdOivIVX4jnXXAZlTKKBxp4')
# Anon key for frontend/client operations (limited access)
SUPABASE_ANON_KEY = os.getenv('SUPABASE_ANON_KEY', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indxb2x1d21kemxqcHZ6aW1qaXlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI3OTc2NjQsImV4cCI6MjA0ODM3MzY2NH0.FdG_DQPoxvFkRCJvCTjdDt5UZVWyZqXAV46_jDNpxqA')
SUPABASE_STORAGE_BUCKET = os.getenv('SUPABASE_STORAGE_BUCKET', 'profile-photos')
SUPABASE_STORAGE_BUCKET_PRESCRIPTIONS = os.getenv('SUPABASE_STORAGE_BUCKET_PRESCRIPTIONS', 'prescriptions')
SUPABASE_STORAGE_BUCKET_NOTIFICATIONS = os.getenv('SUPABASE_STORAGE_BUCKET_NOTIFICATIONS', 'notifications')
