# Generated by Django 5.2.6 on 2025-11-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_rolepermission_notification_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveappointment',
            name='live_appointment_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
