# Generated by Django 5.2.6 on 2025-11-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_liveappointment_live_appointment_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='file',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescription_file',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
