# Generated by Django 5.2.6 on 2025-11-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_notification_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='file',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescription_file',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
