# Generated by Django 5.2.6 on 2025-11-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_notification_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
