# Generated by Django 5.2.6 on 2025-11-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_userprofile_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
